/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FirIdRouteImport } from './routes/$firId'
import { Route as NewRouteImport } from './routes/new'
import { Route as PlaceholdersRouteImport } from './routes/placeholders'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as FirIdEditRouteImport } from './routes/$firId_.edit'
import { Route as TemplatesTemplateIdRouteImport } from './routes/templates_.$templateId'
import { Route as TemplatesNewRouteImport } from './routes/templates_.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FirIdRoute = FirIdRouteImport.update({
  id: '/$firId',
  path: '/$firId',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaceholdersRoute = PlaceholdersRouteImport.update({
  id: '/placeholders',
  path: '/placeholders',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const FirIdEditRoute = FirIdEditRouteImport.update({
  id: '/$firId_/edit',
  path: '/$firId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesTemplateIdRoute = TemplatesTemplateIdRouteImport.update({
  id: '/templates_/$templateId',
  path: '/templates/$templateId',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesNewRoute = TemplatesNewRouteImport.update({
  id: '/templates_/new',
  path: '/templates/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$firId': typeof FirIdRoute
  '/new': typeof NewRoute
  '/placeholders': typeof PlaceholdersRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/$firId/edit': typeof FirIdEditRoute
  '/templates/$templateId': typeof TemplatesTemplateIdRoute
  '/templates/new': typeof TemplatesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$firId': typeof FirIdRoute
  '/new': typeof NewRoute
  '/placeholders': typeof PlaceholdersRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/$firId/edit': typeof FirIdEditRoute
  '/templates/$templateId': typeof TemplatesTemplateIdRoute
  '/templates/new': typeof TemplatesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$firId': typeof FirIdRoute
  '/new': typeof NewRoute
  '/placeholders': typeof PlaceholdersRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/$firId_/edit': typeof FirIdEditRoute
  '/templates_/$templateId': typeof TemplatesTemplateIdRoute
  '/templates_/new': typeof TemplatesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$firId'
    | '/new'
    | '/placeholders'
    | '/settings'
    | '/templates'
    | '/$firId/edit'
    | '/templates/$templateId'
    | '/templates/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$firId'
    | '/new'
    | '/placeholders'
    | '/settings'
    | '/templates'
    | '/$firId/edit'
    | '/templates/$templateId'
    | '/templates/new'
  id:
    | '__root__'
    | '/'
    | '/$firId'
    | '/new'
    | '/placeholders'
    | '/settings'
    | '/templates'
    | '/$firId_/edit'
    | '/templates_/$templateId'
    | '/templates_/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FirIdRoute: typeof FirIdRoute
  NewRoute: typeof NewRoute
  PlaceholdersRoute: typeof PlaceholdersRoute
  SettingsRoute: typeof SettingsRoute
  TemplatesRoute: typeof TemplatesRoute
  FirIdEditRoute: typeof FirIdEditRoute
  TemplatesTemplateIdRoute: typeof TemplatesTemplateIdRoute
  TemplatesNewRoute: typeof TemplatesNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$firId': {
      id: '/$firId'
      path: '/$firId'
      fullPath: '/$firId'
      preLoaderRoute: typeof FirIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/placeholders': {
      id: '/placeholders'
      path: '/placeholders'
      fullPath: '/placeholders'
      preLoaderRoute: typeof PlaceholdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$firId_/edit': {
      id: '/$firId_/edit'
      path: '/$firId/edit'
      fullPath: '/$firId/edit'
      preLoaderRoute: typeof FirIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates_/$templateId': {
      id: '/templates_/$templateId'
      path: '/templates/$templateId'
      fullPath: '/templates/$templateId'
      preLoaderRoute: typeof TemplatesTemplateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates_/new': {
      id: '/templates_/new'
      path: '/templates/new'
      fullPath: '/templates/new'
      preLoaderRoute: typeof TemplatesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FirIdRoute: FirIdRoute,
  NewRoute: NewRoute,
  PlaceholdersRoute: PlaceholdersRoute,
  SettingsRoute: SettingsRoute,
  TemplatesRoute: TemplatesRoute,
  FirIdEditRoute: FirIdEditRoute,
  TemplatesTemplateIdRoute: TemplatesTemplateIdRoute,
  TemplatesNewRoute: TemplatesNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
